### ISSUE TITLE
move all-collections.json gen to here?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/digital_source#8]
currently in main-web-redesign, `assets/data/all-collections.json` generated from `_data/digital_all_collections.csv`

advantage of moving it: 
- the definitive csv is in this repo, so not best to keep multiple versions up-to-date

disadvantage of moving it: 
- all current collectionbuilder-cdm-template collections refer to the main-web version using digital using site.digital-assets which points to the current location. so sort of makes sense to keep all assets in the same place?

**Comment by owikle** [comment]
Decided to keep all-collections.json gen in mainweb in order to keep assets all in one place. Documentation has been updated here: eb820e3cd2989d3a527987a2a14177c1037745c4.
